server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: coderef
            client-secret: $2b$10$ab8I6IMP0TjCyUHZLbQa2.nrsOJRdHGo2FaSkd.vmd/EwKJpdrmYi
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        data: classpath:/sql/data.sql
        driver-class-name: org.postgresql.Driver
        password: 123456
        platform: postgres
        schema: classpath:/sql/schema.sql
        url: jdbc:postgresql://localhost:5433/delivery
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: false
        hibernate:
          ddl-auto: none
        show-sql: true
